server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  absolute_redirect off;

  location = / {
    return 302 /pt-br/;
  }

  location ~ ^/(pt-br|es|en)/?$ {
    try_files /index.html =404;
  }

  location ~ ^/(pt-br|es|en)/blog/?$ {
    try_files /blog.html =404;
  }

  location = /pt-br/projetos/nogueira-cardiologia/ {
    try_files /projects/nogueira-cardiologia/pt-br.html =404;
  }

  location = /es/proyectos/nogueira-cardiologia/ {
    try_files /projects/nogueira-cardiologia/es.html =404;
  }

  location = /en/projects/nogueira-cardiologia/ {
    try_files /projects/nogueira-cardiologia/en.html =404;
  }

  location = /es-ar/ {
    return 301 /es/;
  }

  location = /es-ar/blog/ {
    return 301 /es/blog/;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
